const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const keys={tasks:"dl_tasks_final",goals:"dl_goals_final",notes:"dl_notes_final",profile:"dl_profile_final",reminders:"dl_reminders_final",logged:"dl_logged_final",settings:"dl_settings_final"};
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
let tasks=get(keys.tasks,[]), goals=get(keys.goals,[]), notes=get(keys.notes,{}), profile=get(keys.profile,{name:"Guest",email:"",username:"",bio:"",avatar:"R"}), reminders=get(keys.reminders,[]);
let settings=get(keys.settings,{clock24:false,autoSave:true});
let viewDate=new Date(), selectedDate=new Date(), taskFilter="all", editingTaskId=null, currentNoteKey=null;
const save=()=>{localStorage.setItem(keys.tasks,JSON.stringify(tasks));localStorage.setItem(keys.goals,JSON.stringify(goals));localStorage.setItem(keys.notes,JSON.stringify(notes));localStorage.setItem(keys.profile,JSON.stringify(profile));localStorage.setItem(keys.reminders,JSON.stringify(reminders));localStorage.setItem(keys.settings,JSON.stringify(settings));};
const pad=n=>String(n).padStart(2,"0"), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, todayIso=()=>iso(new Date());
function toast(t){const b=$("#toastBox");b.textContent=t;b.classList.add("show");setTimeout(()=>b.classList.remove("show"),2200)}
function updateIdentity(){let n=profile.name||"Guest", av=(profile.avatar||n[0]||"R").toUpperCase();["sideName","topName","menuName","dashName","profilePreviewName"].forEach(id=>$("#"+id).textContent=n);["sideAvatar","topAvatar","menuAvatar","profileAvatarPreview"].forEach(id=>{$("#"+id).textContent=av});$("#sideStatus").textContent=localStorage.getItem(keys.logged)?"Signed in":"Not signed in";$("#menuEmail").textContent=profile.email||"Guest account";$("#profilePreviewEmail").textContent=profile.email||"Not signed in";$("#profileNameInput").value=profile.name||"";$("#profileEmailInput").value=profile.email||"";$("#profileUsernameInput").value=profile.username||"";$("#profileBioInput").value=profile.bio||"";$("#profileAvatarInput").value=profile.avatar||av}
function showSection(name){$$(".page-section").forEach(x=>x.classList.remove("active"));$("#section-"+name)?.classList.add("active");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.section===name));$("#profileMenu").classList.remove("open");if(name==="dashboard")renderDashboard();if(name==="calendar")renderCalendar();if(name==="tasks")renderTasks();if(name==="goals")renderGoals();if(name==="notes")renderNotes();if(name==="reminders")renderReminders();if(name==="profile")updateIdentity()}
$$("[data-section]").forEach(b=>b.addEventListener("click",()=>showSection(b.dataset.section)));
$("#collapseBtn").onclick=()=>$("#sidebar").classList.toggle("collapsed");
$("#profileTrigger").onclick=()=>$("#profileMenu").classList.toggle("open");
document.addEventListener("click",e=>{if(!e.target.closest(".profile-trigger")&&!e.target.closest(".profile-menu"))$("#profileMenu").classList.remove("open")});
function clock(){let d=new Date(), h=d.getHours(), ap=h>=12?"PM":"AM";let hh=settings.clock24?h:((h+11)%12+1);$("#liveClock").textContent=`${pad(hh)}:${pad(d.getMinutes())}:${pad(d.getSeconds())}${settings.clock24?"":" "+ap}`;$("#topDate").textContent=d.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})}setInterval(clock,1000);clock();

function renderCalendar(){let y=viewDate.getFullYear(),m=viewDate.getMonth();$("#monthTitle").textContent=viewDate.toLocaleDateString(undefined,{month:"long",year:"numeric"});let first=new Date(y,m,1),start=first.getDay(),days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),html="";for(let i=0;i<42;i++){let num=i-start+1,d=new Date(y,m,num),isOther=num<1||num>days;let dIso=iso(d),dayTasks=tasks.filter(t=>t.date===dIso);html+=`<div class="calendar-cell ${isOther?"other":""} ${dIso===todayIso()?"today":""}" data-date="${dIso}"><div class="day-number">${d.getDate()}</div>${dayTasks.slice(0,3).map(t=>`<div class="cell-task ${t.done?"done":""}">${escapeHtml(t.title)}</div>`).join("")}${dayTasks.length>3?`<div class="cell-more">+${dayTasks.length-3} more</div>`:""}</div>`}$("#calendarGrid").innerHTML=html;$$(".calendar-cell").forEach(c=>c.onclick=()=>{selectedDate=new Date(c.dataset.date+"T12:00:00");openTaskModal(c.dataset.date)})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
$("#prevMonth").onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar()};$("#todayBtn").onclick=()=>{viewDate=new Date();renderCalendar()};$("#monthTitleBtn").onclick=()=>openJump();$("#jumpDateBtn").onclick=()=>openJump();$("#addCalendarTask").onclick=()=>openTaskModal(iso(selectedDate));

function openModal(id){$("#"+id).classList.add("open")}function closeModal(id){$("#"+id).classList.remove("open")}
function openTaskModal(date){editingTaskId=null;$("#taskModalTitle").textContent="New task";$("#taskInput").value="";$("#taskDateInput").value=date||todayIso();$("#taskPriority").value="medium";openModal("taskModal")}
$("#addTaskBtn").onclick=()=>openTaskModal(todayIso());$("#closeTask").onclick=$("#cancelTask").onclick=()=>closeModal("taskModal");
$("#saveTask").onclick=()=>{let title=$("#taskInput").value.trim();if(!title)return toast("Please enter a task name.");tasks.push({id:Date.now(),title,date:$("#taskDateInput").value,priority:$("#taskPriority").value,done:false});save();closeModal("taskModal");renderTasks();renderCalendar();renderDashboard();toast("Task added.")};
function renderTasks(){let arr=[...tasks];if(taskFilter==="today")arr=arr.filter(t=>t.date===todayIso());if(taskFilter==="pending")arr=arr.filter(t=>!t.done);if(taskFilter==="completed")arr=arr.filter(t=>t.done);arr.sort((a,b)=>a.date.localeCompare(b.date));$("#allTasksList").innerHTML=arr.length?arr.map(t=>`<div class="task-row ${t.done?"done":""}"><button class="check ${t.done?"done":""}" data-id="${t.id}">${t.done?"✓":""}</button><div class="task-info"><strong>${escapeHtml(t.title)}</strong><small>${t.date} · ${t.priority} priority</small></div><span class="priority-dot priority-${t.priority}"></span><div class="task-actions"><button class="delete-task" data-id="${t.id}"><i class="bi bi-trash3"></i></button></div></div>`).join(""):`<div class="empty">No tasks here yet. Create your first task.</div>`;$$(".task-row .check").forEach(b=>b.onclick=()=>{let t=tasks.find(x=>x.id==b.dataset.id);t.done=!t.done;save();renderTasks();renderCalendar();renderDashboard()});$$(".delete-task").forEach(b=>b.onclick=()=>{tasks=tasks.filter(x=>x.id!=b.dataset.id);save();renderTasks();renderCalendar();renderDashboard()})}
$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");taskFilter=b.dataset.filter;renderTasks()});

function renderDashboard(){let ti=todayIso(),ts=tasks.filter(t=>t.date===ti),done=ts.filter(t=>t.done).length;$("#statTasks").textContent=ts.length;$("#statCompleted").textContent=done;$("#statGoals").textContent=goals.length;$("#statReminders").textContent=reminders.filter(r=>r.date>=ti).length;$("#dashTodayLabel").textContent=new Date().toLocaleDateString(undefined,{month:"long",day:"numeric"});$("#todayTaskList").innerHTML=ts.length?ts.slice(0,5).map(t=>`<div class="list-item"><button class="check ${t.done?"done":""}" data-dash="${t.id}">${t.done?"✓":""}</button><div class="list-main"><strong>${escapeHtml(t.title)}</strong><small>${t.priority} priority</small></div><span class="priority-dot priority-${t.priority}"></span></div>`).join(""):`<div class="empty">Your day is clear. Add a task when you're ready.</div>`;$$("[data-dash]").forEach(b=>b.onclick=()=>{let t=tasks.find(x=>x.id==b.dataset.dash);t.done=!t.done;save();renderDashboard();renderTasks();renderCalendar()});let ups=[...reminders].filter(r=>r.date>=ti).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5);$("#upcomingList").innerHTML=ups.length?ups.map(r=>`<div class="list-item"><div class="reminder-icon"><i class="bi bi-bell"></i></div><div class="list-main"><strong>${escapeHtml(r.title)}</strong><small>${r.date} · ${r.time||"Any time"}</small></div></div>`).join(""):`<div class="empty">No upcoming reminders.</div>`}

function renderGoals(){if(!goals.length){$("#goalGrid").innerHTML='<div class="panel goal-card"><h3>No goals yet</h3><p>Create a goal and start tracking progress.</p></div>';return}$("#goalGrid").innerHTML=goals.map(g=>{let pct=Math.min(100,Math.round(g.progress/g.target*100));return `<div class="panel goal-card"><h3>${escapeHtml(g.title)}</h3><p>Keep moving forward.</p><div class="progress-track"><div class="progress-bar" style="width:${pct}%"></div></div><div class="goal-foot"><span>${g.progress} / ${g.target}</span><span>${pct}%</span></div><div class="goal-actions"><button onclick="changeGoal(${g.id},1)">+ Progress</button><button onclick="deleteGoal(${g.id})">Delete</button></div></div>`}).join("")}
$("#addGoalBtn").onclick=()=>openModal("goalModal");$("#closeGoal").onclick=$("#cancelGoal").onclick=()=>closeModal("goalModal");$("#saveGoal").onclick=()=>{let title=$("#goalInput").value.trim(),target=+$("#goalTarget").value;if(!title)return toast("Enter a goal name.");goals.push({id:Date.now(),title,target:target||1,progress:0});save();closeModal("goalModal");renderGoals();renderDashboard();$("#goalInput").value="";toast("Goal created.")};window.changeGoal=(id,n)=>{let g=goals.find(x=>x.id===id);g.progress=Math.min(g.target,g.progress+n);save();renderGoals();renderDashboard()};window.deleteGoal=id=>{goals=goals.filter(x=>x.id!==id);save();renderGoals();renderDashboard()};

function renderNotes(){let entries=Object.entries(notes).sort((a,b)=>b[0].localeCompare(a[0]));$("#noteDates").innerHTML=entries.length?entries.map(([k,v])=>`<button class="note-date ${k===currentNoteKey?"active":""}" data-note="${k}"><strong>${escapeHtml(v.title||"Untitled")}</strong><br><small>${k}</small></button>`).join(""):`<div class="empty">No notes yet.</div>`;if(!currentNoteKey)currentNoteKey=entries[0]?.[0]||todayIso();let n=notes[currentNoteKey]||{title:"",body:""};$("#noteTitle").value=n.title||"";$("#noteBody").value=n.body||"";$("#noteDateLabel").textContent=currentNoteKey;$$("[data-note]").forEach(b=>b.onclick=()=>{saveCurrentNote();currentNoteKey=b.dataset.note;renderNotes()})}
function saveCurrentNote(){if(!currentNoteKey)return;let title=$("#noteTitle").value.trim(),body=$("#noteBody").value;if(title||body)notes[currentNoteKey]={title,body};else delete notes[currentNoteKey];save()}
$("#saveNoteBtn").onclick=()=>{saveCurrentNote();renderNotes();toast("Note saved.")};$("#newNoteBtn").onclick=()=>{saveCurrentNote();currentNoteKey=todayIso()+"-"+Date.now();notes[currentNoteKey]={title:"",body:""};save();renderNotes()};$("#noteBody").addEventListener("input",()=>{if(settings.autoSave){saveCurrentNote()}});$("#noteTitle").addEventListener("input",()=>{if(settings.autoSave){saveCurrentNote()}});

function renderReminders(){let arr=[...reminders].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$("#reminderList").innerHTML=arr.length?arr.map(r=>`<div class="reminder-row"><div class="reminder-icon"><i class="bi bi-bell"></i></div><div class="reminder-info"><strong>${escapeHtml(r.title)}</strong><small>${r.date} · ${r.time||"Any time"}</small></div><button class="remove-btn" onclick="removeReminder(${r.id})"><i class="bi bi-trash3"></i></button></div>`).join(""):`<div class="empty">No reminders yet.</div>`}
window.removeReminder=id=>{reminders=reminders.filter(r=>r.id!==id);save();renderReminders();renderDashboard();toast("Reminder removed.")};$("#addReminderBtn").onclick=()=>openModal("reminderModal");$("#closeReminder").onclick=$("#cancelReminder").onclick=()=>closeModal("reminderModal");$("#saveReminder").onclick=()=>{let title=$("#reminderInput").value.trim();if(!title)return toast("Enter a reminder.");reminders.push({id:Date.now(),title,date:$("#reminderDate").value||todayIso(),time:$("#reminderTime").value||""});save();closeModal("reminderModal");renderReminders();renderDashboard();$("#reminderInput").value="";toast("Reminder created.")};

function openJump(){openModal("jumpModal");$("#jumpInput").value=iso(viewDate)}$("#closeJump").onclick=$("#cancelJump").onclick=()=>closeModal("jumpModal");$("#applyJump").onclick=()=>{let v=$("#jumpInput").value;if(!v)return;viewDate=new Date(v+"T12:00:00");selectedDate=new Date(viewDate);closeModal("jumpModal");renderCalendar()};

$("#profileSignBtn").onclick=()=>localStorage.getItem(keys.logged)?toast("You're already signed in."):openModal("loginModal");
$("#menuSignIn").onclick=()=>openModal("loginModal");$("#menuSignOut").onclick=$("#signOutBtn").onclick=()=>{localStorage.removeItem(keys.logged);updateIdentity();toast("Signed out.")};$("#closeLogin").onclick=()=>closeModal("loginModal");$("#continueLogin").onclick=()=>{let e=$("#loginEmail").value.trim(),p=$("#loginPassword").value;if(!e||!p)return toast("Enter email and password.");profile.email=e;if(!profile.name||profile.name==="Guest")profile.name=e.split("@")[0];localStorage.setItem(keys.logged,"1");save();closeModal("loginModal");updateIdentity();toast("Signed in. Your local progress is saved.")};$("#googleBtn").onclick=()=>toast("Google sign-in needs a real backend connection.");$("#toggleAuth").onclick=()=>{$("#authTitle").textContent=$("#authTitle").textContent==="Welcome back"?"Create your account":"Welcome back";$("#authSub").textContent=$("#authTitle").textContent==="Create your account"?"Create an account to keep your progress.":"Sign in to save your DayLoom progress.";$("#toggleAuth").textContent=$("#authTitle").textContent==="Create your account"?"I already have an account":"Create one"};

$("#saveProfileBtn").onclick=()=>{profile.name=$("#profileNameInput").value.trim()||"Guest";profile.email=$("#profileEmailInput").value.trim();profile.username=$("#profileUsernameInput").value.trim();profile.bio=$("#profileBioInput").value.trim();profile.avatar=($("#profileAvatarInput").value.trim()||profile.name[0]||"R")[0].toUpperCase();save();updateIdentity();toast("Profile updated.")};

$("#clock24").checked=!!settings.clock24;$("#autoSave").checked=settings.autoSave!==false;$("#clock24").onchange=e=>{settings.clock24=e.target.checked;save();clock()};$("#autoSave").onchange=e=>{settings.autoSave=e.target.checked;save()};$("#exportBtn").onclick=()=>{let blob=new Blob([JSON.stringify({tasks,goals,notes,profile,reminders,settings},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="dayloom-data.json";a.click();URL.revokeObjectURL(a.href);toast("Data exported.")};$("#clearDataBtn").onclick=()=>{if(confirm("Clear all local DayLoom data?")){Object.values(keys).forEach(k=>localStorage.removeItem(k));location.reload()}};

let timerSeconds=25*60,timerRunning=false,timerInt=null;function drawTimer(){let m=Math.floor(timerSeconds/60),s=timerSeconds%60;$("#timer").textContent=`${pad(m)}:${pad(s)}`}function startTimer(){if(timerRunning){clearInterval(timerInt);timerRunning=false;$("#startTimer").innerHTML='<i class="bi bi-play-fill"></i> Start';return}timerRunning=true;$("#startTimer").innerHTML='<i class="bi bi-pause-fill"></i> Pause';timerInt=setInterval(()=>{timerSeconds--;drawTimer();if(timerSeconds<=0){clearInterval(timerInt);timerRunning=false;$("#startTimer").innerHTML='<i class="bi bi-play-fill"></i> Start';toast("Focus session complete!");timerSeconds=25*60;drawTimer()}},1000)}$("#startTimer").onclick=startTimer;$("#resetTimer").onclick=()=>{clearInterval(timerInt);timerRunning=false;timerSeconds=25*60;drawTimer();$("#startTimer").innerHTML='<i class="bi bi-play-fill"></i> Start'};$$(".timer-presets button").forEach(b=>b.onclick=()=>{clearInterval(timerInt);timerRunning=false;timerSeconds=+b.dataset.min*60;drawTimer();$("#startTimer").innerHTML='<i class="bi bi-play-fill"></i> Start'});drawTimer();

updateIdentity();renderDashboard();renderCalendar();renderTasks();renderGoals();renderNotes();renderReminders();
